networks:
  app_network:
 
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: app.py
      SQLALCHEMY_DATABASE_URI: postgresql://postgres:postgres@db:5432/flask_app_db
    command: flask run --host=0.0.0.0
    depends_on:
      - db
    networks:
      - app_network
    
 
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flask_app_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app_network
 
  adminer:
    image: adminer
    ports:
     - "9090:8080"
    networks:
      - app_network
 
volumes:
  db_data: {}
 